updata_time: 2020-01-26-09-25-05
database: qubit_measurement
result_dir: E:/qubit_measurent_20200108
app_info:
  adc_acquire_app: ATS.ats_acquire
  adc_process_app: ATS.ats_result_process
  set_meas_awg_app: AWG.awg_generate_waveform
  find_jpa_working_point_app: jpa.find_jpa_working_point
  single_S21_app1: PNA.S21
  single_S21_app: MW.mw_sweep_one_para
  cavity_shift_app1: ATS.three_dim_S21_with_ATS_sweep_awg_amp
  cavity_shift_app: PNA.three_dim_S21_with_PNA
  vacuum_rabi_splitting_app: ATS.three_dim_S21_with_ATS_sweep_mag_bias
  spectroscopy_line_app: ATS.spectroscopy_line
  three_dim_spectroscopy_app: ATS.three_dim_spectroscopy_sweep_bias
  three_dim_spectroscopy_sweep_z_control_app: ATS.three_dim_spectroscopy_sweep_z_control
  find_readout_freq_app: ATS.find_best_readout_freq
  find_readout_freq_and_amp_app: ATS.find_best_readout_power_and_freq
  find_readout_freq_and_amp_for_single_shot_app: ATS.find_best_readout_power_and_freq_for_single_shot
  rabi_line_sweep_drive_amp_app: single_bit.rabi_line_sweep_drive_amp
  rabi_line_sweep_drive_time_app: single_bit.rabi_line_sweep_drive_time
  T1_line_app: single_bit.T1_line
  ramsey_line_app: single_bit.ramsey_line
  ramsey_sweep_bias_app: single_bit.ramsey_sweep_bias
  echo_line_app: single_bit.echo_line
  RBM_line_app: RBM.RBM_line
  RBM_sweep_f01_and_another_para_app: RBM.RBM_sweep_f01_and_another_para
  three_dim_RBM_sweep_one_para_app: RBM.three_dim_RBM_sweep_one_para
  QST_for_rabi_line_app: QST.QST_for_rabi_line
  QST_for_rabi_line_sweep_drive_amp_app: QST.QST_for_rabi_line_sweep_drive_amp
  QST_for_T1_app: QST.QST_for_T1
  RTO_find_delay_app: RTO.RTO_find_delay
  RTO_line_app: RTO.RTO_line
  xy_z_calibration_app: two_bits.XY_Z_timing_calibration
  z_cross_talk_calibration_app: two_bits.Z_crosstalk_calibration
  state_swap_sweep_bias_app: two_bits.state_swap_line_sweep_bias
  state_swap_sweep_time_app: two_bits.state_swap_line_sweep_time
  three_dim_state_swap_app: two_bits.three_dim_state_swap_sweep_bias_and_time
  cphase_calibration_line_sweep_time_app: two_bits.cPhase_cali_line_sweep_time
  three_dim_cphase_cali_sweep_bias_and_time_app: two_bits.three_dim_cphase_cali_sweep_bias_and_time
  two_qubit_state_prepare_app: two_bits.two_qubit_state_prepare
  two_qubit_state_prepare_and_qst_app: two_bits.two_qubit_state_prepare_and_qst
inst_info:
  drive_awg: AWG5014
  meas_awg: AWG_MEAS
  drive_mw: PSG_DRIVE
  meas_mw: PSG_MEAS
  drive_att: ATT
  meas_att: ATT
  pna: PNA
  RSA: RSA
  ADC: ATS
jpa_info:
  bias_inst: DC3
  bias_ch: 1
  bias_amp: 0.074
  drive_mw: PSG_JPA
  drive_amp: 8.75
  drive_freq: 13107000000.0
adc_info:
  n: 1024
  ARange: 2.0
  BRange: 2.0
  repeats: 2048
  maxlen: 2048
  bufferCount: 2048
  trigLevel: 0.5
  triggerDelay: 0
  triggerTimeout: 10
  average: true
pna_info:
  Power: -40
  center: 6582000000.0
  span: 10.0
  points: 3
  Bandwidth: 100
  Output: ON
  digital_delay: 1e-08
  phase_compensate: false
  timeout: 200
drive_info:
  mw_freq: 4400000000.0
  mw_power: 20
  carry:
    Q1: -144000000.0
    Q2: -144000000.0
    Q3: -144000000.0
    Q4: -144000000.0
    Q5: -158000000.0
    Q6: -283000000.0
    Q7: -400000000.0
    Q8: -400000000.0
    Q9: -69600000.0
    Q10: -248000000.0
  IQ_cali_array:
    Q5:
    - - 0.97
      - -0.0136
      - 0.0
    - - 1.0
      - 0.0086
      - -2.4
    Q6:
    - - 0.974
      - -0.0136
      - 0.0
    - - 1.0
      - 0.0086
      - 1.5
    Q7:
    - - 0.974
      - -0.0136
      - 0.0
    - - 1.0
      - 0.0086
      - 1.5
    Q8:
    - - 0.982
      - -0.0136
      - 0.0
    - - 1.0
      - 0.0086
      - -3.02
    Q9:
    - - 0.993
      - -0.0135
      - 0.0
    - - 1.0
      - 0.0015
      - -0.2
    Q10:
    - - 0.983
      - -0.0135
      - 0.0
    - - 1.0
      - 0.0015
      - 1.5
  cross_talk_matrix:
  - - 1
    - -0.03
  - - 0.0
    - 1
  sRate: 1200000000.0
  pulse_length: 0.0003
  only_one_awg: false
meas_info:
  mw_freq: 6630000000.0
  mw_power: 23
  carry:
    Q1: -162730000.0
    Q2: -150530000.0
    Q3: -138500000.0
    Q4: -126800000.0
    Q5: -111373000.0
    Q6: -97573000.0
    Q7: -83500000.0
    Q8: -71600000.0
    Q9: -55850000.0
    Q10: -40500000.0
  IQ_cali_array:
    Q3:
    - - 1.004
      - 0.007
      - 0.0
    - - 1.0
      - -0.001
      - -31.05
    Q4:
    - - 1.004
      - 0.007
      - 0.0
    - - 1.0
      - -0.001
      - -31.05
    Q5:
    - - 1.004
      - 0.007
      - 0.0
    - - 1.0
      - -0.001
      - -31.05
    Q6:
    - - 1.003
      - 0.007
      - 0.0
    - - 1.0
      - -0.001
      - -26.875
    Q7:
    - - 1.0025
      - 0.007
      - 0.0
    - - 1.0
      - -0.001
      - -22.6
    Q8:
    - - 1.002
      - 0.007
      - 0.0
    - - 1.0
      - -0.001
      - -18.9
    Q9:
    - - 1.0015
      - 0.007
      - 0.0
    - - 1.0
      - -0.001
      - -14.5
    Q10:
    - - 1.0025
      - 0.007
      - 0.0
    - - 1.0
      - -0.001
      - -9.9
  meas_delay: -4.5e-07
  ADC_triger_delay: 4e-07
  sRate: 1200000000.0
  pulse_length: 0.0003
  only_one_awg: false
qubit_info:
  Q1:
    bias_inst: DC2
    bias_ch: 1
    bias_amp: 0.0
    I_ch: 1
    Q_ch: 2
    marker_ch: 1
    z_ch: 3
    bare_freq: 6465000000.0
    disp_freq: 6467270000.0
    disp_amp: 0.05
    probe_freq: 6467270000.0
    probe_amp: 0.1
    readout_base: 1.0
    rabi_amp: 1.0
    f01_r: 4256260000.0
    f01: 4256000000.0
    an_harmonicity: 250000000.0
    drive_power: 16
    drive_att: 0
    drive_amp: 1.0
    meas_power: 23
    meas_att: 0
    pi_array:
    - 2e-08
    - 0.276
    - 2e-08
    - 0.138
    swap_array:
    - 1e-08
    - 0.2
    - 2e-08
    - 0.2
    DRAG_ratio: -0.13
    Z_XY_delay: 9e-09
    pulse_type: CosPulse
    single_shot_array:
    - 0
    - 1
    - 1
    - 0
  Q2:
    bias_inst: DC2
    bias_ch: 2
    bias_amp: 0.0
    I_ch: 1
    Q_ch: 2
    marker_ch: 1
    z_ch: 3
    bare_freq: 6477690000.0
    disp_freq: 6479470000.0
    disp_amp: 0.05
    probe_freq: 6479470000.0
    probe_amp: 0.1
    readout_base: 1.0
    rabi_amp: 1.0
    f01_r: 4256260000.0
    f01: 4256000000.0
    an_harmonicity: 250000000.0
    drive_power: 16
    drive_att: 0
    drive_amp: 1.0
    meas_power: 23
    meas_att: 0
    pi_array:
    - 2e-08
    - 0.276
    - 2e-08
    - 0.138
    swap_array:
    - 1e-08
    - 0.2
    - 2e-08
    - 0.2
    DRAG_ratio: -0.13
    Z_XY_delay: 9e-09
    pulse_type: CosPulse
    single_shot_array:
    - 0
    - 1
    - 1
    - 0
  Q3:
    bias_inst: DC2
    bias_ch: 3
    bias_amp: 0.0
    I_ch: 1
    Q_ch: 2
    marker_ch: 1
    z_ch: 3
    bare_freq: 6490500000.0
    disp_freq: 6491500000.0
    disp_amp: 0.05
    probe_freq: 6491500000.0
    probe_amp: 0.1
    readout_base: 1.0
    rabi_amp: 1.0
    f01_r: 4256260000.0
    f01: 4256000000.0
    an_harmonicity: 250000000.0
    drive_power: 16
    drive_att: 0
    drive_amp: 1.0
    meas_power: 23
    meas_att: 0
    pi_array:
    - 2e-08
    - 0.276
    - 2e-08
    - 0.138
    swap_array:
    - 1e-08
    - 0.2
    - 2e-08
    - 0.2
    DRAG_ratio: -0.13
    Z_XY_delay: 9e-09
    pulse_type: CosPulse
    single_shot_array:
    - 0
    - 1
    - 1
    - 0
  Q4:
    bias_inst: DC3
    bias_ch: 2
    bias_amp: -0.05
    I_ch: 1
    Q_ch: 2
    marker_ch: 1
    z_ch: 3
    bare_freq: 6503440000.0
    disp_freq: 6504500000.0
    disp_amp: 0.05
    probe_freq: 6503200000.0
    probe_amp: 0.1
    readout_base: 1.0
    rabi_amp: 1.0
    f01_r: 4256260000.0
    f01: 4256000000.0
    an_harmonicity: 250000000.0
    drive_power: 16
    drive_att: 0
    drive_amp: 1.0
    meas_power: 23
    meas_att: 0
    pi_array:
    - 2e-08
    - 0.276
    - 2e-08
    - 0.138
    swap_array:
    - 1e-08
    - 0.2
    - 2e-08
    - 0.2
    DRAG_ratio: -0.13
    Z_XY_delay: 9e-09
    pulse_type: CosPulse
    single_shot_array:
    - 0
    - 1
    - 1
    - 0
  Q5:
    bias_inst: DC3
    bias_ch: 3
    bias_amp: -0.102
    I_ch: 1
    Q_ch: 2
    marker_ch: 1
    z_ch: 3
    bare_freq: 6517530000.0
    disp_freq: 6519297000.0
    disp_amp: 0.05
    probe_freq: 6518627000.0
    probe_amp: 0.1
    readout_base: 1.0
    rabi_amp: 1.0
    f01_r: 4242000000.0
    f01: 4242000000.0
    f02: 4104000000.0
    an_harmonicity: 250.0
    drive_power: 16
    drive_att: 0
    drive_amp: 1.0
    meas_power: 23
    meas_att: 0
    pi_array:
    - 2e-08
    - 0.32
    - 2e-08
    - 0.16
    swap_array:
    - 1e-08
    - 0.2
    - 2e-08
    - 0.2
    DRAG_ratio: 0.0
    Z_XY_delay: 9e-09
    marker_delay: -9e-09
    pulse_type: CosPulse
    single_shot_array:
    - 0
    - 1
    - 1
    - 0
  Q6:
    bias_inst: DC3
    bias_ch: 4
    bias_amp: 0.02
    I_ch: 1
    Q_ch: 2
    marker_ch: 2
    z_ch: 4
    bare_freq: 6531750000.0
    disp_freq: 6532297000.0
    disp_amp: 0.05
    probe_freq: 6532427000.0
    probe_amp: 0.1
    readout_base: 1.0
    rabi_amp: 1.0
    f01_r: 4117000000.0
    f01: 4117000000.0
    an_harmonicity: 250.0
    drive_power: 16
    drive_att: 0
    drive_amp: 1.0
    meas_power: 23
    meas_att: 0
    pi_array:
    - 2e-08
    - 0.4
    - 2e-08
    - 0.2
    swap_array:
    - 1e-08
    - 0.2
    - 2e-08
    - 0.2
    DRAG_ratio: 0.0
    Z_XY_delay: 9e-09
    marker_delay: -9e-09
    pulse_type: CosPulse
    single_shot_array:
    - 0
    - 1
    - 1
    - 0
  Q7:
    bias_inst: DC1
    bias_ch: 1
    bias_amp: 0.1
    I_ch: 1
    Q_ch: 2
    marker_ch: 1
    z_ch: 3
    bare_freq: 6545520000.0
    disp_freq: 6547557000.0
    disp_amp: 0.05
    probe_freq: 6546500000.0
    probe_amp: 0.1
    readout_base: 1.0
    rabi_amp: 1.0
    f01_r: 4000000000.0
    f01: 4000000000.0
    an_harmonicity: 250.0
    drive_power: 16
    drive_att: 0
    drive_amp: 1.0
    meas_power: 23
    meas_att: 0
    pi_array:
    - 2e-08
    - 0.276
    - 2e-08
    - 0.138
    swap_array:
    - 1e-08
    - 0.2
    - 2e-08
    - 0.2
    DRAG_ratio: -0.13
    Z_XY_delay: 9e-09
    marker_delay: -9e-09
    pulse_type: CosPulse
    single_shot_array:
    - 0
    - 1
    - 1
    - 0
  Q8:
    bias_inst: DC1
    bias_ch: 2
    bias_amp: -0.15
    I_ch: 1
    Q_ch: 2
    marker_ch: 1
    z_ch: 3
    bare_freq: 6558760000.0
    disp_freq: 6560860000.0
    disp_amp: 0.05
    probe_freq: 6558400000.0
    probe_amp: 0.1
    readout_base: 1.0
    rabi_amp: 1.0
    f01_r: 4000000000.0
    f01: 4000000000.0
    an_harmonicity: 250.0
    drive_power: 16
    drive_att: 0
    drive_amp: 1.0
    meas_power: 23
    meas_att: 0
    pi_array:
    - 2e-08
    - 0.276
    - 2e-08
    - 0.138
    swap_array:
    - 1e-08
    - 0.2
    - 2e-08
    - 0.2
    DRAG_ratio: -0.13
    Z_XY_delay: 9e-09
    marker_delay: -9e-09
    pulse_type: CosPulse
    single_shot_array:
    - 0
    - 1
    - 1
    - 0
  Q9:
    bias_inst: DC1
    bias_ch: 3
    bias_amp: 0.0085
    I_ch: 1
    Q_ch: 2
    marker_ch: 1
    z_ch: 3
    bare_freq: 6572760000.0
    disp_freq: 6574950000.0
    disp_amp: 0.05
    probe_freq: 6574150000.0
    probe_amp: 0.1
    readout_base: 0.121
    rabi_amp: 0.104
    f01_r: 4330400000.0
    f01: 4330400000.0
    f12: 4048000000.0
    an_harmonicity: 250.0
    drive_power: 16
    drive_att: 0
    drive_amp: 1.0
    meas_power: 23
    meas_att: 0
    pi_array:
    - 2e-08
    - 0.42
    - 2e-08
    - 0.21
    cphase_array:
    - 1.6e-08
    - -0.188
    swap_array:
    - 2e-08
    - 0.05
    - 1e-08
    - 0.05
    couple_off_bias: 0.0
    DRAG_ratio: -0.07
    Z_XY_delay: -3e-09
    marker_delay: -9e-09
    pulse_type: CosPulse
    single_shot_array:
    - 0.09463495741411063
    - -0.07883775088648252
    - -0.0008264182559637573
    - -0.01864827903985177
  Q10:
    bias_inst: DC1
    bias_ch: 4
    bias_amp: 0.1475
    I_ch: 1
    Q_ch: 2
    marker_ch: 2
    z_ch: 4
    bare_freq: 6588500000.0
    disp_freq: 6590460000.0
    disp_amp: 0.05
    probe_freq: 6589500000.0
    probe_amp: 0.095
    readout_base: 0.173
    rabi_amp: 0.115
    f01_r: 4152000000.0
    f01: 4152000000.0
    f12: 3890000000.0
    an_harmonicity: 260.0
    drive_power: 16
    drive_att: 0
    drive_amp: 1.0
    meas_power: 23
    meas_att: 0
    pi_array:
    - 2e-08
    - 0.424
    - 2e-08
    - 0.212
    cphase_array:
    - 1.9e-08
    - -0.188
    swap_array:
    - 2e-08
    - 0.05
    - 1e-08
    - 0.05
    couple_off_bias: 0.0
    DRAG_ratio: 0.03
    Z_XY_delay: -2e-09
    marker_delay: -9e-09
    pulse_type: CosPulse
    single_shot_array:
    - 0.16786228340162132
    - 0.04845574707554612
    - 0.031921966685112615
    - 0.04592801910999722
